version: '3.8'

services:

  django:
    build:
      context: .
    volumes:
      - media:/app/media
      - static:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    volumes:
        - postgres-data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWD}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWD}
        - POSTGRES_DB=${DB_DATABASE}

  nginx:
    build: ./nginx
    volumes:
      - media:/app/media
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static:
  media:
  postgres-data:
