http:
  routers:
    traefik:
      rule: "Host(`traefik.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "localhost"
            sans:
              - "*.localhost"


tls:
  certificates:
    - certFile: "/etc/certs/certificate.pem"
      keyFile: "/etc/certs/privatekey.pem"
