version: "3"

networks:
  gitea:
    external: false

services:
  gitserv:
    image: gitea/gitea:1.18.5
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:${DB_PORT}
      - GITEA__database__NAME=${POSTGRES_DB_NAME}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      - GITEA__server__HTTP_PORT=${GIT_PORT}
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${IP_ADDR}:${GIT_PORT}:${GIT_PORT}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: DB-${CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - ${IP_ADDR}:${DB_PORT}:${DB_PORT}
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
